### ISSUE TITLE
why const: Assertion `data_.size() % 8 == 0' failed？ (Use CLion)

### ISSUE THREAD

**Issue by qiujinfa** [dkales/dpf-cpp#1]
dpf_pir: /home/XXX/CLionProjects/dpf-cpp/hashdatastore.cpp:316: hashdatastore::hash_type hashdatastore::answer_pir2(const std::vector<unsigned char>&) const: Assertion `data_.size() % 8 == 0' failed.

**Comment by dkales** [comment]
The included hashdatastore just assumes that the number of stored data items is a multiple of 8. This is just for convenience as it processes them 8 at a time for better pipelining, but this is not a necessity.
You can either pad your items with dummy items to get it to a multiple of 8, or modify the code to handle the last few (<8) items separately.

**Comment by qiujinfa** [comment]
Thank you.
